# Generated by Django 4.2 on 2026-08-24 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_workingday_workinghours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slot_granularity_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
