# Generated by Django 4.2 on 2026-08-24 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_business_slot_granularity_minutes_alter_business_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('client_name', models.CharField(max_length=150)),
                ('client_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='confirmed', max_length=20)),
                ('cancellation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='agenda.business')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='agenda.service')),
            ],
        ),
    ]
