# Generated by Django 4.2 on 2026-08-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_title', models.CharField(blank=True, max_length=120)),
                ('public_description', models.TextField(blank=True, max_length=500)),
                ('cta_label', models.CharField(default='Agendar agora', max_length=40)),
                ('theme', models.CharField(choices=[('ocean', 'Azul oceano'), ('forest', 'Verde floresta'), ('sunset', 'Pôr do sol')], default='ocean', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='agenda.business')),
            ],
        ),
    ]
