# Generated by Django 4.2 on 2026-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_businesspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído'), ('no_show', 'Não compareceu')], default='confirmed', max_length=20),
        ),
    ]
