# Generated by Django 4.2 on 2026-08-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_customer_appointment_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('appointment_created', 'Novo agendamento'), ('appointment_cancelled', 'Agendamento cancelado')], max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='agenda.appointment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='agenda.business')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
