# Generated by Django 4.2 on 2026-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_businessnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
