# Generated by Django 6.1 on 2026-08-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_business_whatsapp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspage',
            name='primary_color',
            field=models.CharField(blank=True, default='#087f82', max_length=7),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='secondary_color',
            field=models.CharField(blank=True, default='#d88d4d', max_length=7),
        ),
    ]
