# Generated by Django 6.1 on 2026-08-26 00:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_businesspage_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='whatsapp_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='whatsapp_opt_in_source',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='whatsapp_reminder_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_reminder_lead_time_minutes',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_reminders_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WhatsAppIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, max_length=100)),
                ('access_token_env_var', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connected', 'Conectado'), ('error', 'Com erro')], default='disconnected', max_length=20)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_integration', to='agenda.business')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='appointment_reminder', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='agenda.appointment')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='reminder_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'kind'), name='unique_reminder_kind_per_appointment')],
            },
        ),
    ]
