# Generated by Django 6.1 on 2026-08-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_appointment_whatsapp_opt_in_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentreminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
