# Generated by Django 6.1 on 2026-08-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_appointmentreminder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappintegration',
            old_name='access_token_env_var',
            new_name='api_key_env_var',
        ),
        migrations.RenameField(
            model_name='whatsappintegration',
            old_name='phone_number_id',
            new_name='instance_name',
        ),
    ]
