# Generated by Django 6.1 on 2026-08-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_rename_access_token_env_var_whatsappintegration_api_key_env_var_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='whatsapp_reminder_message',
            field=models.CharField(default='Olá, {cliente}! Lembrete: seu atendimento de {servico} está marcado para {data} às {hora}.', max_length=500),
        ),
    ]
